### ISSUE TITLE
更新后，没有目录了

### ISSUE THREAD

**Issue by ShomyLiu** [someus/huno#11]
您好，今天下午更新之后，目录不见了。。另外还有一个问题是，标签，分类怎么无法显示呢？

**Comment by someus** [comment]
请问是什么目录，详细一些。

**Comment by ShomyLiu** [comment]
就是右下角的  toc 按钮

**Comment by someus** [comment]
你的是最新的版本吗？Hexo 3.1，我在3.1测试没有问题的。能否把Firbug控制台的输出截个图给我？

**Comment by ShomyLiu** [comment]
![github](http://img.blog.csdn.net/20151129012410028)

**Comment by ShomyLiu** [comment]
hexo是最新的，昨天才下载的。另外，您这个主题不支持 widgets里面的tags 或者标签云之类的吗？麻烦了

**Comment by someus** [comment]
1、看下主题的配置文件中有没有配置`awesome_toc: true`，而且awesome_toc只在每篇文章中显示。

2、Firebug等调试工具的network选项中查看有没有加载awesome-toc.min.js。

3、标签云请参考[https://github.com/someus/huno#%E5%BD%92%E6%A1%A3%E9%A1%B5%E9%9D%A2](https://github.com/someus/huno#%E5%BD%92%E6%A1%A3%E9%A1%B5%E9%9D%A2)

**Comment by ShomyLiu** [comment]
谢谢，现在已经可以了，应该是浏览器缓存的问题，谢谢
