### ISSUE TITLE
替换主题后报错...

### ISSUE THREAD

**Issue by ccguo** [someus/huno#12]
安装hexo 以后，使用默认主题能够运行，将hexo配置文件中主题名字改为huno,发生错误

Unhandled rejection TypeError: /Users/ccguo/Documents/jekyll/blog_hexo/themes/huno/layout/layout.ejs:68
    66|     </span>
    67| 
 >> 68|     <%- partial('_partials/side-panel') %>
    69| 
    70|     <div class="content-wrapper">
    71|         <div class="content-wrapper__inner entry">

/Users/ccguo/Documents/jekyll/blog_hexo/themes/huno/layout/_partials/side-panel.ejs:46
    44|           </nav>
    45| 
 >> 46|           <%- partial('_partials/social') %>
    47| 
    48|         </div>
    49| 

/Users/ccguo/Documents/jekyll/blog_hexo/themes/huno/layout/_partials/social.ejs:52
    50|   <ul class="navigation">
    51| 
 >> 52|     <% if (config.social.github){ %>
    53|       
    54|       <li class="navigation__item">
    55|         <a href="https://github.com/<%= config.social.github %>" title="Huno on GitHub">

Cannot read property 'github' of undefined

**Comment by someus** [comment]
感谢反馈。

这个错误涉及到这个[socail icon 功能](https://github.com/someus/huno#social-icon)。

现在已经修复。
