### ISSUE TITLE
希望能增加的点

### ISSUE THREAD

**Issue by CatchZeng** [someus/huno#16]
能否在新版本中增加一个站内搜索功能？
能否增加额外的社交，比如：微博、简书、微信、qq之类的？

**Comment by someus** [comment]
站内搜索用 http://www.sogou.com/docs/features.htm#30  或者  https://swiftype.com/  就行了  就是一段代码的事情， 可以自己添加。  

我用的图标库中没有国内的网站的图标，刚搜了一下  http://www.zcool.com.cn/gfx/ZMzM1MjEy.html 看起来很不错， 过段时间闲下来的时候我会搞一下。

也欢迎你贡献代码^^

**Comment by someus** [comment]
国内网站图标已经加上，具体可以看下readme.md，欢迎反馈。
