### ISSUE TITLE
为什么文章列表中, 不显示文章内容呢

### ISSUE THREAD

**Issue by zzyspace** [someus/huno#18]
标题下面是空的, 没有文字. 你的Demo中第一页的也是这样, 但是第二页的又是正常的, 请问是要配置什么东西吗

**Comment by zzyspace** [comment]
明白了, markdown文件中使用就可以了

**Comment by LAKEX** [comment]
@zzyspace  我也遇到了同样的困难,但由于个人只是有限,没有解决,请问可以告诉我具体怎么做吗?：）
