### ISSUE TITLE
请问怎么设置RSS？？

### ISSUE THREAD

**Issue by DearZack** [someus/huno#20]

**Comment by someus** [comment]
[http://hanhailong.com/2015/10/08/Hexo%E2%80%94%E6%AD%A3%E7%A1%AE%E6%B7%BB%E5%8A%A0RSS%E8%AE%A2%E9%98%85/](http://hanhailong.com/2015/10/08/Hexo%E2%80%94%E6%AD%A3%E7%A1%AE%E6%B7%BB%E5%8A%A0RSS%E8%AE%A2%E9%98%85/)


我没在主题上设置显示RSS按钮的功能，需要自己添加。
