### ISSUE TITLE
关于在Mac上生成的public文件的一些错误情况

### ISSUE THREAD

**Issue by MonFig** [someus/huno#32]
1、在生成public文件后，打开index.html文件直接出线侧图页面，无法出现全图首页。
2、加载的样式表和js文件路径错误，自动生成的"/css/style.css"等应为"css/style.css"，js与之相同。
3、点击HEXO，本来应该出现全图首页，却直接跳转到了电脑的根目录，考虑是"href=/"引起的。
以上问题仅在搭载OS X的MacBook上的chrome浏览器中确认，均未尝试在其他平台复现。

**Comment by someus** [comment]
抱歉，这个问题我没法复现。这些路径理论上是没问题的。你可以根据自己的需要去修改。
