### ISSUE TITLE
how to generate the elements of the tags and categories page？

### ISSUE THREAD

**Issue by doesnta** [someus/huno#9]
I new the tags and categories page，（Because it didn't have one）hoping to create page include all the tags or categories and also their links.

But i dont't know how to,is this theme didn't contain the method to do that?

**Comment by doesnta** [comment]
and also a bug repo in the phone，

![7b1d95f7e130570baf4c16484f3503bc](https://cloud.githubusercontent.com/assets/14181649/9984782/eb398248-6050-11e5-8737-3c10b003bffe.png)

```java
when i  folder the navigation bar,the icon of the bar is wrong.
```

I think is the click function logic,you must using the same bar click function in all the page,but you forget to folder the bar automatically or judge the navigation status 。

unfortunately,I only know same jquery and nothing node.js.
And you seem to give up this project already,it's  so pity.
I love this theme,it's beautiful.Thanks~~~~~

**Comment by someus** [comment]
Just like `http://wuchong.me/jacman/`，hexo has the function that generate tags in a page. I advise that  you can learn how to create an hexo theme from [https://hexo.io/docs/themes.html](https://hexo.io/docs/themes.html).  Then you can customize themes yourself. Sorry for that I do not have enough to solve the problem.

**Comment by doesnta** [comment]
@someus  I'M alway confusing about how hexo generate the html page automatically.
Thanks.I will have a look.
